CREATE DATABASE IF NOT EXISTS  desafio_ciee;
USE desafio_ciee;
-- A tabela DEVELOPER se refere a desenvolvedora para fazer as relacoes 1-N
CREATE TABLE IF NOT EXISTS DEVELOPER(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DEVELOPER_NAME VARCHAR(255) UNIQUE NOT NULL
    );
-- A tabela GENDERS se refere aos generos para fazer as relacoes 1-N
CREATE TABLE IF NOT EXISTS GENDER(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GENDER VARCHAR(100) UNIQUE NOT NULL
    );
-- A tabela GAME faz a referencia as outras tabelas contendo mais informacoes para as outras duas tabelas
CREATE TABLE IF NOT EXISTS GAME(
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    TITLE VARCHAR(100) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    LAUNCH_DATE YEAR NOT NULL,
    DEVELOPER INT NOT NULL,
    GENDER INT NOT NULL,
    GENDERII INT ,
    GENDERIII INT ,
    GENDERIV INT ,
    GENDERV INT ,
    FOREIGN KEY(DEVELOPER) REFERENCES DEVELOPER(ID),
    FOREIGN KEY(GENDER) REFERENCES GENDER(ID),
    FOREIGN KEY(GENDERII) REFERENCES GENDER(ID),
    FOREIGN KEY(GENDERIII) REFERENCES GENDER(ID),
    FOREIGN KEY(GENDERIV) REFERENCES GENDER(ID),
    FOREIGN KEY(GENDERV) REFERENCES GENDER(ID)
    );
